[package]
name = "enum_index_repr"
version = "0.2.1"
edition = "2021"
description = "EnumIndexRepr provides a small macro which allows getting the index on an enum."
license = "MIT"

exclude = [
    "example/*",
]

[dependencies]
enum_index_repr_derive = "0.2"
