[package]
name = "enum_index_repr_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0.98", features = ["full", "fold", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0.40"

[lib]
proc-macro = true

